spring.application.name=smart-luggage-backend
server.port=${SERVER_PORT:8195}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
debug=false
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}
app.pricing.base-fee=2500
app.pricing.rate-per-kg=900
